### ISSUE TITLE
Add support for HOMEBREW environment variables

### ISSUE THREAD

**Issue by glodov** [redis-stack/redis-stack#161] opened 2022-07-13 09:21 UTC
My current directory is `~/homebrew/` but when installing redis-stack part of the files are installed into `/opt/homebrew/`.
And this directory `/opt/homebrew/` did not exist, so I created it and also linked installed modules by `ln -s ~/homebrew/opt /opt/homebrew/opt` to make it work by loading installed modules.

So I fixed the installation by creating links.

**Comment by chayim** [comment] 2022-07-18 14:35
@glodov is your homebrew updated? It appears that older versions of homebrew allowed for ~/homebrew/ but an active decision was made to ensure that on arm (M1), things are in ```/opt/homebrew```, and that on x86_64 these are in ```/usr/local/```.

Alternatively do you have any environment variables for homebrew set - something that makes your directory ```~/homebrew```? I'd like to get the right support in there.

**Comment by glodov** [comment] 2022-07-18 14:48
Thanks, @chayim !
My version and paths are
```bash
% brew config | grep "HOME"
HOMEBREW_VERSION: 3.5.4
HOMEBREW_PREFIX: /Users/yaro/homebrew
HOMEBREW_REPOSITORY: /Users/yaro/homebrew
HOMEBREW_CELLAR: /Users/yaro/homebrew/Cellar
```
And the terminal $PATH is:
```bash
% echo $PATH
/Users/yaro/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/yaro/.cargo/bin
```
Is this info enough?

**Comment by glodov** [comment] 2022-07-19 10:25
Sure, @chayim !

I prefer to use `ls -lah` to see more details.
```bash
 % ls -lah ~/homebrew
total 96
drwxr-xr-x   31 yaro  staff   992B Jul 13 09:48 .
drwxr-xr-x+  57 yaro  staff   1.8K Jul 18 17:42 ..
-rw-r--r--    1 yaro  staff    51B Dec  4  2021 .dockerignore
-rw-r--r--    1 yaro  staff   467B Dec  4  2021 .editorconfig
drwxr-xr-x   13 yaro  staff   416B Jul 18 17:52 .git
drwxr-xr-x   10 yaro  staff   320B Jun 29 12:34 .github
-rw-r--r--    1 yaro  staff   7.9K Jun 29 12:34 .gitignore
-rw-r--r--    1 yaro  staff   1.3K Dec  4  2021 .shellcheckrc
drwxr-xr-x    3 yaro  staff    96B Dec  4  2021 .sublime
-rw-r--r--    1 yaro  staff    65B Dec  4  2021 .vale.ini
drwxr-xr-x    4 yaro  staff   128B Dec  4  2021 .vscode
-rw-r--r--    1 yaro  staff   207B Dec  4  2021 CHANGELOG.md
-rw-r--r--    1 yaro  staff   829B Dec  4  2021 CONTRIBUTING.md
drwxrwxr-x    5 yaro  admin   160B Jul 13 10:32 Caskroom
drwxr-xr-x   76 yaro  staff   2.4K Jul 14 13:49 Cellar
-rw-r--r--    1 yaro  staff   1.8K May 26 13:31 Dockerfile
drwxr-xr-x    4 yaro  staff   128B May 26 13:51 Frameworks
-rw-r--r--    1 yaro  staff   1.3K Dec  4  2021 LICENSE.txt
drwxr-xr-x    7 yaro  staff   224B Jul 13 09:41 Library
-rw-r--r--    1 yaro  staff   7.8K May 26 13:31 README.md
drwxr-xr-x  355 yaro  staff    11K Jul 18 17:55 bin
drwxr-xr-x    7 yaro  staff   224B Dec  4  2021 completions
drwxr-xr-x   72 yaro  staff   2.3K Jul 13 09:41 docs
drwxr-xr-x   28 yaro  staff   896B Jul 14 13:50 etc
drwxr-xr-x  142 yaro  staff   4.4K Jul 18 17:55 include
drwxr-xr-x  249 yaro  staff   7.8K Jul 18 17:54 lib
drwxr-xr-x    4 yaro  staff   128B Jul 13 09:41 manpages
drwxr-xr-x  105 yaro  staff   3.3K Jul 18 17:55 opt
drwxr-xr-x    6 yaro  staff   192B Dec  4  2021 sbin
drwxr-xr-x   35 yaro  staff   1.1K Jul 18 17:55 share
drwxr-xr-x    9 yaro  staff   288B Jun 29 12:37 var
```

**Comment by chayim** [comment] 2022-07-28 05:56
@glodov awesome - thanks a bunch. There's a new release of redis-stack coming shortly (as in next couple of days). I'm going to update the homebrew recipe after that, to support this use case.  I'd like to have fewer moving parts.

Let's expect something to land early next week if it all pans out. I'm also pretty sure I can do something to unit test this purely thanks to everything you've shared.  

VERY MUCH APPRECIATED!

**Comment by glodov** [comment] 2022-07-28 18:41
Thank you for your cooperation @chayim !
If you let me know when it's ready by message here, I can test it on my machine.

**Comment by chayim** [comment] 2022-08-01 06:59
@glodov So... I have a fix, and yet I can't test or reproduce your issue.  I've pushed [this branch](https://github.com/redis-stack/homebrew-redis-stack/tree/ck-brewcustom) to the homebrew recipe world. Can you kindly test in your environment?

I've tried setting all of your variables, - but it appears that homebrew doesn't see them. Can you please let me know if my branch works, in your environment?

This may also just be a cask issue - as casks are different. But, that would make this unsolvable, which I don't like.

**Comment by chayim** [comment] 2022-08-21 06:25
@glodov bump

**Comment by vicjohnson1213** [comment] 2022-10-14 22:39
Hi @chayim, I'm also running into this issue. I checked out the changes you've made on ck-brewcustom and was able to successfully install those three formulae.

I'm now getting an error when actually running the `redis-stack-server`:
```
...
27471:M 14 Oct 2022 18:11:06.449 * Module 'search' loaded from /Users/vic/.homebrew/Caskroom/redis-stack-server/6.2.4-v1/lib/redisearch.so
27471:M 14 Oct 2022 18:11:06.678 # Module /Users/vic/.homebrew/Caskroom/redis-stack-server/6.2.4-v1/lib/redisgraph.so failed to load: dlopen(/Users/vic/.homebrew/Caskroom/redis-stack-server/6.2.4-v1/lib/redisgraph.so, 0x0006): Library not loaded: /opt/homebrew/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/vic/.homebrew/Caskroom/redis-stack-server/6.2.4-v1/lib/redisgraph.so
  Reason: tried: '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file)
27471:M 14 Oct 2022 18:11:06.678 # Can't load module from /Users/vic/.homebrew/Caskroom/redis-stack-server/6.2.4-v1/lib/redisgraph.so: server aborting
```

I took a look around the RedisGraph repo and it looks like it's already using `brew --prefix` ([see here](https://github.com/RedisGraph/RedisGraph/blob/59472b620c4aa447b688521b13457d5c99466e3e/src/Makefile#L85)). I'm by no means an expert with c++ or Make, but it looks like I might just have an old binary?

A little more info for you:
```
brew config | grep "HOME":
  HOMEBREW_VERSION: 3.6.5
  HOMEBREW_PREFIX: /Users/vic/.homebrew
  HOMEBREW_REPOSITORY: /Users/vic/.homebrew
  HOMEBREW_CELLAR: /Users/vic/.homebrew/Cellar
  HOMEBREW_CASK_OPTS: []
  HOMEBREW_MAKE_JOBS: 10

brew --prefix libomp:
  /Users/vic/.homebrew/opt/libomp
```

Let me know if I can share any additional diagnostics.

**Comment by chayim** [comment] 2022-11-13 07:07
@vicjohnson1213 Thanks for looking into this! Based on the branch, and other things in the mix - I think this was just bad timing, across multiple operating systems. I've updated the branch with the latest changes, which have long since addressed the redisgraph issue.  Mind having a look :pray: I believe the changes for ```basepath``` address both the M1 and original intel use cases.

**Comment by chayim** [comment] 2023-05-07 10:36
basepath is set - closing accordingly.

**Closed by chayim** 2023-05-07 10:36 UTC
Labels: enhancement
